// Todos los textos de interfaz (UI-20, TR-111). Literales del Apéndice A de docs/06 (UI-21).
// Una cadena nueva se añade aquí Y al Apéndice A en el mismo PR: textos.test.ts lo comprueba.
// Lo que va entre corchetes en el apéndice es un parámetro de la función correspondiente.

type Parametro = string | number;

export const T = {
  app: {
    nombre: 'Protección Civil Albolote',
    nombreCorto: 'Hidrantes',
    entornoPruebas: 'ENTORNO DE PRUEBAS',
    cargando: 'Cargando…',
  },

  navegacion: {
    mapa: 'Mapa',
    lista: 'Lista',
    ajustes: 'Ajustes',
    puntosDeAgua: 'Puntos de agua',
    misPropuestas: 'Mis propuestas',
    nuevoPunto: 'Nuevo punto',
    jefatura: 'Jefatura',
  },

  entrada: {
    codigo: 'Código de acceso del grupo',
    nombre: 'Nombre',
    apellido: 'Apellido',
    entrar: 'Entrar',
    soloUnaVez: 'Solo se pide una vez: este móvil recordará tu acceso y tu nombre.',
    jefaturaGoogle: '¿Eres de jefatura? Entrar con Google',
    avisoLegal: 'Aviso legal y privacidad',
    codigoIncorrecto: 'Código incorrecto',
    demasiadosIntentos: 'Demasiados intentos. Espera una hora antes de volver a intentarlo.',
    noAutorizado: 'No autorizado',
    noAutorizadoDetalle:
      'Tu cuenta de Google no está en la lista de administradores de hidrantes. Pide a jefatura que la añada desde Ajustes del panel.',
    sinAcceso: 'Sin acceso',
    volver: 'Volver',
    cifra: (n: Parametro) => `Cifra ${n} de 6`,
    codigoSeisCifras: 'El código son 6 cifras',
    faltaNombre: 'Escribe tu nombre y apellido',
    entrando: 'Entrando…',
    sinServidor: 'Sin conexión con el servidor. Inténtalo de nuevo en un momento.',
    accesoCaducado: 'El acceso de este móvil ya no vale. Vuelve a escribir el código del grupo; tu nombre se conserva.',
    comprobandoCuenta: 'Comprobando tu cuenta…',
    avisoLegalVersion: (version: Parametro) => `Aviso legal y privacidad · v${version}`,
    avisoLegalTitulo: 'Aviso legal',
  },

  bienvenida: {
    pantallas: [
      {
        titulo: 'Cuanto más grande, más agua da',
        texto:
          'Círculo = hidrante, cuadrado = boca de riego. El color dice el estado; el tamaño, lo aprovechable que es. Un borde discontinuo significa que nadie lo ha revisado en más de un año.',
      },
      {
        titulo: 'Añadir un punto son cuatro toques',
        texto:
          'Pulsa +, ajusta el pin, elige tipo y estado, haz la foto. Sin cobertura también: se enviará solo cuando vuelva la señal.',
      },
      {
        titulo: 'Todo pasa por jefatura',
        texto:
          'Lo que propongas no aparece en el mapa hasta que jefatura lo apruebe. Te avisaremos del resultado, y si algo se rechaza, del motivo.',
      },
    ],
    siguiente: 'Siguiente',
    empezar: 'Empezar',
    saltar: 'Saltar',
    paso: (n: Parametro) => `Pantalla ${n} de 3`,
  },

  legal: {
    titulo: 'Mapa de hidrantes — aviso legal y privacidad',
    introduccion:
      'Esta aplicación la usa la Agrupación de Voluntarios de Protección Civil de Albolote para mantener el inventario de hidrantes y bocas de riego del término municipal y de Calicasas.',
    secciones: [
      {
        titulo: 'Qué guardamos de ti.',
        texto:
          'Tu nombre y apellido, para saber quién aportó cada dato, y un identificador aleatorio de tu móvil, para reconocer tus propias propuestas. No guardamos tu teléfono, correo, DNI ni dirección. Tu nombre solo lo ve la jefatura; nunca otros voluntarios.',
      },
      {
        titulo: 'Ubicación y fotos.',
        texto:
          'Al proponer un punto se guarda la posición del punto y, como referencia para jefatura, la de tu móvil en ese momento. Las fotos se guardan sin metadatos. No fotografíes personas ni matrículas: el objeto de la foto es el hidrante.',
      },
      {
        titulo: 'Cuánto tiempo.',
        texto:
          'El historial de cambios se conserva mientras exista el inventario, porque es el registro de quién hizo qué. Si dejas la agrupación y quieres que tu nombre desaparezca, pídelo a jefatura: lo sustituimos por "voluntario dado de baja" conservando los datos del hidrante.',
      },
      {
        titulo: 'Tus derechos.',
        texto:
          'Puedes pedir a jefatura ver, corregir o anonimizar lo que consta de ti. La responsable del tratamiento es la agrupación, representada por su jefatura.',
      },
      {
        titulo: 'Datos externos.',
        texto:
          'Para deducir direcciones se consulta OpenStreetMap con las coordenadas del hidrante, nunca con datos tuyos. Mapa base y direcciones © OpenStreetMap contributors.',
      },
    ],
  },

  mapa: {
    buscar: 'Buscar código, calle, dirección o coordenadas…',
    capas: 'Capas',
    // Atribuciones de las capas: las exigen sus licencias y se ven en el mapa.
    atribucionOsm: '© OpenStreetMap contributors',
    atribucionPnoa: 'PNOA © Instituto Geográfico Nacional',
    atribucionCatastro: '© Dirección General del Catastro',
    atribucionBase: '© OpenStreetMap contributors · Protomaps',
    mapaBasePropio: 'Mapa base propio',
    calleOsm: 'Calle (OSM)',
    satelitePnoa: 'Satélite (PNOA)',
    catastro: 'Catastro',
    necesitaCobertura: 'necesita cobertura',
    miPosicion: 'Mi posición',
    sincronizado: (hace: Parametro) => `Sincronizado ${hace}`,
    sinCobertura: (hace: Parametro) => `Sin cobertura · datos de ${hace}`,
    sinServidor: 'Sin conexión con el servidor',
    sinEnviar: (n: Parametro) => `${n} sin enviar`,
    todos: 'Todos',
    hidrantes: 'Hidrantes',
    bocas: 'Bocas',
    noFunciona: 'No funciona',
    sinRevisar: 'Sin revisar',
    revisado: (hace: Parametro) => `revisado ${hace}`,
    leyendaTamano: 'Más grande = más agua aprovechable',
    desdeTi: 'desde ti',
    desdeIncidente: 'desde el incidente',
    filtroVacio: 'Nada coincide con ese filtro.',
    sinCoberturaSolo: 'Sin cobertura',
    reintentar: 'Reintentar',
    nPuntos: (n: Parametro) => `${n} puntos`,
    sincronizando: 'Sincronizando…',
    sinPuntos: 'Todavía no hay puntos guardados en este móvil. Se descargarán en cuanto haya conexión.',
    // Ya sincronizado y el servidor no tiene ninguno: el primer día de producción (DEC-051, docs/20 RV-76).
    inventarioVacio:
      'Todavía no hay ningún punto en el inventario. Mantén pulsado el mapa donde haya uno para darlo de alta.',
    anadirUnPunto: 'Añadir un punto',
    mapaNoDescargado:
      'Mapa base no descargado. Sin cobertura solo se ven los puntos. Descárgalo en Ajustes cuando tengas wifi.',
    mapabaseFalta: 'El mapa base no está en el móvil: sin cobertura el fondo quedará vacío.',
    descargarMapabase: (mb: Parametro) => `Descargar (${mb} MB)`,
    descargarVersionNueva: 'Descargar versión nueva',
    ocultarAviso: 'Ocultar aviso',
    capaSinCobertura: (capa: Parametro) =>
      `La capa "${capa}" necesita cobertura. Los puntos siguen; cambia al mapa base.`,
    capaConBaseDebajo: (capa: Parametro) => `Sin cobertura: se ve el mapa base propio en lugar de «${capa}»`,
    busquedaVacia: 'Nada coincide con esa búsqueda.',
    borrarBusqueda: 'Borrar búsqueda',
    buscandoPosicion: 'Buscando tu posición…',
    posicionDenegada: 'Sin permiso de ubicación: actívalo en los ajustes del móvil para centrar el mapa en ti.',
    posicionNoDisponible: 'No se puede obtener tu posición ahora mismo.',
    leyenda: 'Leyenda',
    acercar: 'Acercar',
    alejar: 'Alejar',
    funcionaSinCobertura: 'funciona sin cobertura',
    soloEnLinea: 'solo en línea',
    orden: 'Orden',
    filtrar: 'Filtrar',
    porDistancia: 'distancia',
    porCodigo: 'código',
    porEstado: 'estado',
    gps: (metros: Parametro) => `GPS ±${metros} m`,
  },

  ficha: {
    direccion: 'Dirección',
    ultimaRevision: 'Última revisión',
    aTi: 'A ti',
    sinDireccion: 'sin dirección',
    caducada: 'caducada',
    proponerCambio: 'Proponer un cambio',
    comoLlegar: 'Cómo llegar',
    datosDe: (hace: Parametro) => `Datos de ${hace} · sin cobertura`,
    ampliar: 'ampliar',
    cerrar: 'Cerrar',
    noEncontrado: 'Punto no encontrado.',
    datosSincronizados: (hace: Parametro) => `Datos sincronizados ${hace}`,
    fallo: 'Fallo:',
    racor: (racor: Parametro) => `Racor ${racor}`,
    fotoNoDisponible: 'Foto no disponible sin cobertura',
    sinFoto: 'Sin foto',
  },

  // Funciones de mapa para emergencias (FR-72, FR-75; docs/18 GM-02 y GM-05).
  coordenadas: {
    titulo: 'Coordenadas',
    decimal: 'Decimal',
    utm: 'UTM ETRS89 · huso 30',
    copiar: (que: Parametro) => `Copiar ${que}`,
    copiado: 'Copiado',
    noSeCopia: 'No se ha podido copiar: mantén pulsado el texto para copiarlo',
  },

  aqui: {
    titulo: '¿Qué hay aquí?',
    cercanosDesdeAqui: 'Cercanos desde aquí',
    compartirUbicacion: 'Compartir esta ubicación',
    anadirPunto: 'Añadir un punto aquí',
    junto: (calle: Parametro) => `Junto a ${calle}`,
  },

  // Búsqueda de calles, lugares, direcciones y coordenadas (FR-73, docs/18 GM-04).
  busqueda: {
    coordenadas: (decimal: Parametro) => `Coordenadas ${decimal}`,
    fueraDeZona: 'Fuera de la zona habitual',
    /** Longitud escrita sin signo que se ha tomado como oeste (docs/19 RV-69). */
    tomadoComoOeste: (numero: Parametro) => `Se ha tomado ${numero} como Oeste`,
    enlaceCorto: 'Abre el enlace en el navegador y copia las coordenadas',
    puntos: 'Puntos',
    calles: 'Calles y lugares',
    direcciones: 'Direcciones',
    fuenteCalles: '© OpenStreetMap',
    fuenteDirecciones: 'CartoCiudad · IGN',
    buscandoDirecciones: 'Buscando la dirección…',
    sinDirecciones: 'Ninguna dirección con ese número en Albolote ni Calicasas',
    portalSinCobertura: 'Los números de portal necesitan cobertura: te enseño la calle',
    portalSinAcceso: 'Vuelve a entrar con el código para buscar números de portal',
    municipio: { albolote: 'Albolote', calicasas: 'Calicasas' },
  },

  incidente: {
    boton: 'Cercanos',
    titulo: 'Cercanos',
    diana: 'Incidente',
    desdeTuPosicion: 'Desde tu posición',
    desdePuntoMarcado: 'Desde el punto marcado',
    posicionDe: (hace: Parametro) => `Posición de ${hace}`,
    soloHidrantes: 'Solo hidrantes',
    lineaRecta: 'Distancias en línea recta',
    sinPosicion: 'Sin posición: mantén pulsado el mapa donde está el incidente o busca la calle',
    buscandoPosicion: 'Buscando tu posición… (puedes marcar el incidente en el mapa)',
    precision: (m: Parametro) => `±${m} m`,
    pocoPrecisa: (m: Parametro) => `Posición poco precisa (±${m} m): si sabes dónde es, mantén pulsado el mapa`,
    marcarEnMapa: 'Marcar en el mapa',
    vacio: 'Ningún punto que funcione a menos de 2 km del incidente',
    verTodos: 'Ver todos en la lista',
    masCercanoNoFunciona: (codigo: Parametro, distancia: Parametro) =>
      `El más cercano, ${codigo} a ${distancia}, no funciona`,
    masCercanoMalo: (codigo: Parametro, distancia: Parametro) =>
      `El más cercano, ${codigo} a ${distancia}, está en mal estado`,
    fila: (distancia: Parametro, rumbo: Parametro, tramos: Parametro) => `${distancia} · ${rumbo} · ${tramos}`,
    tramos: (n: Parametro) => (n === 1 ? '≥ 1 tramo' : `≥ ${n} tramos`),
    compartirIncidente: 'Compartir el incidente',
    datos: (hace: Parametro) => `Datos de ${hace}`,
    desdeIncidente: 'Distancias desde el incidente',
    cerrarIncidente: 'Cerrar el incidente',
    ampliarHoja: 'Ver más cercanos',
    volverALista: 'Volver a la lista',
    volverACercanos: 'Volver a Cercanos',
    reducirHoja: 'Ver más mapa',
  },

  medir: {
    boton: 'Medir',
    titulo: 'Medir distancia',
    desdeAqui: 'Medir desde aquí',
    tendido: 'Medir tendido',
    empezar: 'Toca el mapa para poner los puntos del tendido',
    resultado: (distancia: Parametro, n: Parametro, largo: Parametro) =>
      n === 1 ? `${distancia} · 1 tramo de ${largo} m` : `${distancia} · ${n} tramos de ${largo} m`,
    deshacer: 'Deshacer',
    borrar: 'Borrar',
    terminar: 'Terminar',
    motivoDeshacer: 'Para deshacer hacen falta dos puntos',
    motivoBorrar: 'Aún no hay puntos: toca el mapa',
  },

  compartir: {
    boton: 'Compartir',
    tituloUbicacion: 'Ubicación',
    lineaPunto: (codigo: Parametro, tipo: Parametro, diametro: Parametro, estado: Parametro) =>
      `${codigo} · ${tipo} ${diametro} · ${estado}`,
    lineaCoordenadas: (decimal: Parametro, utm: Parametro) => `${decimal} · UTM ${utm} (ETRS89)`,
    copiado: 'Copiado: pégalo donde quieras',
    noSePuede: 'No se ha podido compartir ni copiar: mantén pulsado el texto para copiarlo',
  },

  operaciones: {
    queHaCambiado: (codigo: Parametro) => `¿Qué ha cambiado en ${codigo}?`,
    sigueIgual: 'Sigue igual',
    sigueIgualDetalle: 'Solo actualiza la fecha de revisión. Foto y listo.',
    actualizarEstado: 'Actualizar estado',
    actualizarEstadoDetalle: 'El caudal ha cambiado o ya no funciona',
    corregirDatos: 'Corregir datos',
    corregirDatosDetalle: 'Diámetro, racor o descripción mal anotados',
    tipoNoCambia: '¿El tipo está mal? Propón retirarlo y da de alta el correcto',
    corregirUbicacion: 'Corregir ubicación',
    corregirUbicacionDetalle: 'El pin está desplazado',
    proponerRetirada: 'Proponer retirada',
    proponerRetiradaDetalle: 'Ya no existe. Pide un motivo breve',
    etiquetaAlta: 'Alta',
    etiquetaRevision: 'Revisión',
    etiquetaEstado: 'Estado',
    etiquetaDatos: 'Datos',
    etiquetaUbicacion: 'Ubicación',
    etiquetaRetirada: 'Retirada',
    constaComo: (estado: Parametro, hace: Parametro) => `Consta como ${estado} · revisado ${hace}`,
    caudalAhora: 'Caudal / estado ahora',
    revisionAviso: 'Confirmas que el punto sigue exactamente igual. Solo cambia la fecha de última revisión.',
    retiradaAviso:
      'Solo jefatura puede confirmar la retirada. Hasta entonces el punto sigue en el mapa de todos, y en el histórico quedará siempre que aquí hubo un punto.',
    jefaturaAviso:
      'Entraste con Google: el cambio se aplica al momento y consta en el registro como acción tuya. No pasa por la cola.',
    ubicacionAyuda: 'Toca el mapa donde está realmente. La posición anterior queda registrada.',
    sinGps: 'Sin posición GPS: toca el mapa donde está el punto.',
    tuGpsDetalle: (precision: Parametro, distancia: Parametro) => `±${precision} m · a ${distancia} del pin`,
    phFallo: 'Qué impide usarlo',
    phNota: 'Ej.: sale menos fuerza que en mayo',
    phMotivo: 'Qué has encontrado en el sitio',
    phOtraMedida: 'Medida en mm (jefatura la comprobará)',
    preparandoFoto: 'Preparando la foto…',
    fotoIlegible: 'No se pudo leer la foto. Prueba otra vez.',
    enviando: 'Enviando…',
    guardadoDetalle: 'Se enviará sola cuando haya conexión.',
    aplicadoDetalle: 'El cambio ya está en el mapa de todos.',
    errorGuardar: 'No se pudo guardar en el móvil. Inténtalo otra vez.',
  },

  formulario: {
    tipoElemento: 'Tipo de elemento',
    hidrante: 'Hidrante',
    bocaRiego: 'Boca de riego',
    diametro: 'Diámetro de la salida mayor',
    d70: '70 mm',
    d100: '100 mm',
    otraMedida: 'Otra medida',
    diametroAyuda: 'La salida, no la tubería. Si hay varias, marca la mayor',
    diametroBoca: '45 mm · fijo en bocas de riego',
    racor: 'Racor · compara con lo que ves',
    granada: 'Granada',
    barcelona: 'Barcelona',
    otro: 'Otro',
    caudal: 'Caudal / estado',
    bueno: 'Bueno',
    regular: 'Regular',
    malo: 'Malo',
    noFunciona: 'No funciona',
    caudalAyuda: 'Malo = probado y sale débil. No funciona = no se pudo probar (tapa, válvula, arqueta).',
    descripcionFallo: 'Descripción del fallo · obligatoria',
    foto: 'Foto',
    fotoDeHoy: 'Foto de hoy',
    fotoDelSitio: 'Foto del sitio',
    hacerFoto: 'Hacer foto · obligatoria',
    fotoAnadida: (kb: Parametro) => `Foto añadida · ${kb} kB`,
    repetir: 'repetir',
    descripcionOpcional: 'Descripción (opcional)',
    descripcionAyuda: 'Referencia de calle, acceso…',
    notaOpcional: 'Nota (opcional)',
    desplazamiento: 'Desplazamiento',
    tuGps: 'Tu GPS',
    porQueRetirada: '¿Por qué ya no existe?',
    obras: 'Obras',
    asfaltado: 'Asfaltado',
    sustituido: 'Sustituido',
    motivoRetirada: 'Cuéntalo brevemente · obligatorio',
  },

  avisosFormulario: {
    faltaFoto: 'Falta la foto para poder enviar',
    eligeEstado: 'Elige el estado',
    describeFallo: 'Describe el fallo',
    eligeTipo: 'Elige el tipo',
    eligeDiametro: 'Elige el diámetro',
    indicaMedida: 'Indica la medida',
    eligeRacor: 'Elige el racor',
    muevePin: 'Mueve el pin al sitio correcto',
    sinCambios: 'No has cambiado nada',
    eligeMotivo: 'Elige un motivo',
    explicaMotivo: 'Explica brevemente qué has visto',
    fueraDeZona: '⚠ Esto queda fuera de la zona habitual. Puedes continuar; jefatura lo verá señalado.',
    ajustaPin: (metros: Parametro) => `Toca el mapa para ajustar el pin · el círculo azul es tu GPS (±${metros} m)`,
    posicionNoAlDia: 'La posición no está al día: coloca el pin a mano o espera a que el GPS responda',
  },

  envio: {
    enviarRevision: 'Enviar para revisión',
    enviarRetirada: 'Enviar propuesta de retirada',
    aplicarAhora: 'Aplicar ahora',
    guardarSinCobertura: 'Guardar · se enviará con cobertura',
    guardarSinServidor: 'Guardar · se enviará al volver el servidor',
    enviado: 'Enviado para revisión',
    guardadoEnMovil: 'Guardado en el móvil',
    soloEnMemoria: 'Sin guardar en el móvil',
    soloEnMemoriaDetalle: 'No se ha podido guardar en el móvil. No cierres la aplicación hasta que se envíe.',
    reintentarAhora: 'Reintentar ahora',
    aplicado: 'Aplicado',
    volverAlMapa: 'Volver al mapa',
    verMisPropuestas: 'Ver mis propuestas',
    jefaturaRevisara: 'Jefatura lo revisará. Te avisaremos del resultado al abrir la aplicación.',
    avisoSinCobertura: 'Sin cobertura · lo que envíes se guardará en el móvil y saldrá al recuperar señal',
    avisoSinServidor:
      'Sin conexión con el servidor · seguimos con los datos guardados; lo que envíes esperará y se reintentará solo',
  },

  misPropuestas: {
    pendiente: 'Pendiente',
    aprobada: 'Aprobada',
    rechazada: 'Rechazada',
    retiradaPorTi: 'Retirada por ti',
    sinEnviar: 'Sin enviar',
    retirar: 'Retirar',
    motivo: (texto: Parametro) => `Motivo: ${texto}`,
    conCorrecciones: (texto: Parametro) => `con correcciones: ${texto}`,
    esperando24h: '⚠ Lleva más de 24 h esperando cobertura. Se enviará sola al tener señal.',
    vacio: 'Todavía no has propuesto nada. Desde la ficha de un punto o con el botón + del mapa.',
    resumen: (enviadas: Parametro, sinEnviar: Parametro) => `${enviadas} enviadas · ${sinEnviar} sin enviar`,
    nuevo: 'nuevo',
    descartar: 'Descartar',
    reintentar: 'Reintentar',
    confirmarDescartar: '¿Descartar este envío?',
    descartarDetalle: 'No se ha podido enviar y ya no se enviará. No se puede deshacer.',
    confirmarRetirar: '¿Retirar esta propuesta?',
    retirarDetalle: 'Jefatura ya no la verá. No se puede deshacer.',
    aprobadaAviso: (codigo: Parametro) => `Aprobada ${codigo}`,
    rechazadaAviso: (codigo: Parametro) => `Rechazada ${codigo}`,
    errorNoActivo: 'El punto ya no está activo: no se ha enviado.',
    errorDatos: 'Faltan datos o no son válidos: no se ha enviado.',
    errorFoto: 'Falta la foto: no se ha enviado.',
    errorTipo: 'El tipo de un punto no se cambia: propón retirarlo y da de alta el correcto.',
    errorGenerico: 'No se ha podido enviar.',
    yaRevisada: 'Jefatura ya la ha revisado',
    errorRetirar: 'No se ha podido retirar. Inténtalo de nuevo.',
    listaGuardada: 'Sin conexión: esta es la última lista guardada.',
  },

  ajustes: {
    firma: 'Firma de tus propuestas',
    cambiar: 'Cambiar',
    mapaSinCobertura: 'Mapa sin cobertura',
    descargado: (mb: Parametro, fecha: Parametro) => `Descargado · ${mb} MB · ${fecha}`,
    noDescargado: 'No descargado',
    descargar: 'Descargar',
    actualizar: 'Actualizar',
    puntosGuardados: 'Puntos guardados',
    sincronizar: 'Sincronizar',
    capaPorDefecto: 'Capa por defecto',
    modoOscuro: 'Modo oscuro',
    segunMovil: 'Según el móvil',
    avisarResolucion: 'Avisarme cuando jefatura resuelva mis propuestas',
    algoNoFunciona: 'Algo no funciona en la aplicación',
    avisarJefatura: 'Avisar a jefatura',
    comoSeUsa: 'Cómo se usa (3 pantallas)',
    cerrarSesion: 'Cerrar sesión en este móvil',
    cerrarSesionDetalle: 'Se borran tu acceso, tu nombre y los puntos guardados.',
    versionNueva: 'hay una versión nueva, recargar',
    novedades: 'novedades',
    seccionNovedades: 'Novedades',
    nuevo: 'Nuevo',
    sinNovedades: 'Todavía no hay novedades publicadas.',
    cuentaJefatura: 'Cuenta de jefatura',
    sesionGoogle: (correo: Parametro) => `Sesión de Google · ${correo}`,
    cerrarSesionGoogle: 'Cerrar la sesión de Google',
    ver: 'Ver',
    siempre: 'Siempre',
    nunca: 'Nunca',
    guardar: 'Guardar',
    cancelar: 'Cancelar',
    pantalla: 'Pantalla',
    ayuda: 'Ayuda',
    confirmarCerrar: '¿Cerrar sesión en este móvil?',
    cerrarSesionBoton: 'Cerrar sesión',
    version: (version: Parametro) => `Versión ${version}`,
    descargando: (porcentaje: Parametro) => `Descargando… ${porcentaje} %`,
    noDescargadoDetalle: 'No descargado · el mapa no tendrá calles sin cobertura',
    versionNuevaMapa: 'Hay una versión nueva del mapa',
    falloDescarga: 'No se pudo descargar. Inténtalo de nuevo con wifi.',
    puntosGuardadosDetalle: (n: Parametro, hace: Parametro) => `${n} · sincronizado ${hace}`,
    sinSincronizar: 'Todavía sin sincronizar',
    guardadoProtegido: 'Guardado protegido',
    guardadoProtegidoValor: (si: boolean) => (si ? 'sí' : 'no'),
    avisos: 'Avisos',
    perderasEnvios: (n: Parametro) => `Tienes ${n} envíos sin mandar: se perderán.`,
  },

  incidencia: {
    intro: 'Para problemas de la aplicación. Si lo que quieres es cambiar un hidrante, hazlo desde su ficha.',
    queHaPasado: 'Qué ha pasado',
    ph: 'Ej.: al hacer la foto la app se cierra…',
    seEnviaCon: (version: Parametro) =>
      `Se enviará con la versión (${version}) y la pantalla en la que estabas. Lo verá jefatura en su panel.`,
    describe: 'Describe el problema',
    enviado: 'Aviso enviado a jefatura',
    cuota: 'Ya has enviado varios avisos hoy. Inténtalo mañana.',
  },

  instalar: {
    titulo: 'Instalar la aplicación',
    boton: 'Instalar',
    aviso: 'Instala la aplicación en la pantalla de inicio: se abre más rápido y funciona sin cobertura.',
    instalada: 'Instalada en este móvil',
    ios: 'En iPhone: Compartir → Añadir a pantalla de inicio.',
    menu: 'En el menú del navegador: Añadir a pantalla de inicio (o Instalar aplicación).',
  },

  push: {
    titulo: 'Avisos de jefatura',
    explicacion:
      'Recibirás una notificación cuando una propuesta tuya se apruebe o se rechace. Nada más: ni de otros voluntarios ni publicidad. En iPhone solo funciona si la aplicación está instalada en la pantalla de inicio. El móvil te pedirá permiso ahora.',
    permitir: 'Permitir avisos',
    ahoraNo: 'Ahora no',
    activado: 'Activado en este móvil',
    desactivado: 'Desactivado · también verás el resultado al abrir la app',
    denegado: 'Avisos bloqueados en el móvil: actívalos en sus ajustes.',
    instalarPrimero:
      'En iPhone, primero añade la aplicación a la pantalla de inicio (Compartir → Añadir a pantalla de inicio).',
    reintentar: 'Reintentar',
    cerrar: 'Cerrar',
    permisoNoConcedido:
      'El móvil no ha dejado preguntar. Abre los ajustes de notificaciones de la aplicación, actívalas y vuelve a intentarlo.',
    permisoBloqueado:
      'Los avisos de esta aplicación están bloqueados en el móvil. En Android: Ajustes → Aplicaciones → esta aplicación → Notificaciones. Actívalas y vuelve aquí.',
    sinServicioPush:
      'Este móvil no puede recibir avisos ahora (servicio de avisos no disponible). Comprueba que tiene conexión y los servicios de Google actualizados.',
    sinServiceWorker: 'La aplicación aún se está preparando. Ciérrala del todo, ábrela y vuelve a intentarlo.',
    claveDistinta:
      'No se ha podido renovar la suscripción de avisos de este móvil. Vuelve a intentarlo; si sigue igual, avísalo desde «Algo no funciona en la aplicación», aquí en Ajustes.',
    servidorSinConexion: 'Sin conexión con el servidor. Vuelve a intentarlo cuando tengas cobertura.',
    servidorNoGuarda:
      'El servidor no ha guardado la suscripción. Vuelve a intentarlo; si sigue igual, avísalo desde «Algo no funciona en la aplicación», aquí en Ajustes.',
    referencia: (motivo: Parametro) => `Referencia para jefatura: ${motivo}`,
  },

  fallo: {
    titulo: 'Algo ha fallado en esta pantalla',
    detalle: 'Queda anotado para jefatura. Lo que tenías guardado sigue en el móvil.',
  },

  jefatura: {
    panel: 'Panel de jefatura',
    irAlMapa: 'Ir al mapa',
  },

  formato: {
    haceUnMomento: 'hace un momento',
    haceMin: (n: Parametro) => `hace ${n} min`,
    haceHoras: (n: Parametro) => `hace ${n} h`,
    haceUnDia: 'hace 1 día',
    haceDias: (n: Parametro) => `hace ${n} días`,
    haceUnMes: 'hace 1 mes',
    haceMeses: (n: Parametro) => `hace ${n} meses`,
    haceUnAno: 'hace 1 año',
    haceAnos: (n: Parametro) => `hace ${n} años`,
    mm: (n: Parametro) => `${n} mm`,
  },

  panelCola: {
    colaRevision: 'Cola de revisión',
    inventario: 'Inventario',
    revisionesCaducadas: 'Revisiones caducadas',
    registro: 'Registro',
    papelera: 'Papelera',
    voluntarios: 'Voluntarios',
    ajustes: 'Ajustes',
    buscar: 'Buscar código, calle o voluntario…',
    pendientes: 'Pendientes',
    aprobadas: 'Aprobadas',
    rechazadas: 'Rechazadas',
    retiradasPorAutor: 'Retiradas por el autor',
    ningunaSeleccionada: 'Ninguna seleccionada',
    seleccionadas: (n: Parametro) => `${n} seleccionadas`,
    aprobarSeleccionadas: 'Aprobar seleccionadas',
    rechazarSeleccionadas: 'Rechazar seleccionadas…',
    todasOperaciones: 'todas las operaciones',
    todosNucleos: 'todos los núcleos',
    aprobar: 'Aprobar',
    aprobarConCorrecciones: 'Aprobar con correcciones',
    guardarYAprobar: 'Guardar y aprobar',
    rechazar: 'Rechazar…',
    confirmarRechazo: 'Confirmar rechazo',
    fusionarCon: (codigo: Parametro) => `Fusionar con ${codigo}`,
    confirmarYAprobar: 'Confirmar y aprobar',
    cancelar: 'Cancelar',
    motivoRechazo: 'Motivo del rechazo (obligatorio, lo verá quien lo propuso)',
    sinMotivo: 'Sin motivo no se puede rechazar.',
    desactualizada: (cuando: Parametro) =>
      `El diff está calculado sobre un estado que ya no existe: el punto cambió ${cuando}. Se pide confirmación expresa en lugar del botón normal.`,
    posibleDuplicado: 'Posible duplicado: compara antes de decidir. En ámbar, lo que difiere.',
    colaVacia: 'No queda ninguna propuesta pendiente. Buen trabajo.',
    deducidaEditable: 'deducida · editable',
    delPunto: 'del punto',
    fueraDeZona: 'Fuera de zona',
    sinNucleo: 'sin núcleo',
    ninguno: 'ninguno',
    nuevo: 'nuevo',
    campoTipo: 'Tipo',
    campoDiametro: 'Diámetro',
    campoRacor: 'Racor',
    campoEstado: 'Estado',
    campoFallo: 'Fallo',
    campoDescripcion: 'Descripción',
    campoNota: 'Nota',
    campoRevision: 'Revisión',
    campoDesplazamiento: 'Desplazamiento',
    campoSituacion: 'Situación',
    campoMotivo: 'Motivo',
    activo: 'Activo',
    retirado: 'Retirado',
    sinCambios: (valor: Parametro) => `${valor} · sin cambios`,
    otraMedida: (mm: Parametro) => `Otra medida: ${mm} mm`,
    senalGps: (precision: Parametro, distancia: Parametro) => `GPS en campo · ±${precision} m · a ${distancia} del pin`,
    senalManual: 'Pin puesto a mano',
    senalManualLejos: (distancia: Parametro) => `Pin puesto a mano · a ${distancia} del GPS del móvil`,
    senalGpsImpreciso: (metros: Parametro) => `GPS poco preciso · ±${metros} m`,
    senalFotoLejos: (distancia: Parametro) => `La foto se hizo a ${distancia} del pin`,
    senalRevisionAnterior: (cuando: Parametro) => `Revisión anterior: ${cuando}`,
    esteMes: 'este mes',
    senalDuplicado: (codigo: Parametro, distancia: Parametro) => `Posible duplicado de ${codigo} · a ${distancia}`,
    senalOtraMedida: 'Diámetro "otra medida": hay que fijar 70 o 100 mm',
    senalDesactualizada: 'El punto cambió después de esta propuesta',
    conFoto: 'Con foto',
    fijaDiametro: 'Fija el diámetro en 70 o 100 mm para poder aprobar.',
    pinPropuesto: (distancia: Parametro) => `la del pin propuesto (a ${distancia})`,
    ubicacionDe: (codigo: Parametro) => `la de ${codigo} (existente)`,
    omitidaDesactualizada: 'desactualizada',
    omitidaPuntoNoActivo: 'el punto ya no está activo',
    omitidaDiametro: 'diámetro sin fijar',
    omitidaYaResuelta: 'ya estaba resuelta',
    omitidaDatos: 'datos no válidos',
    omitidaTipo: 'cambia el tipo, que no se puede cambiar: recházala',
    loteAprobadas: (n: Parametro) => `${n} aprobadas, cada una con su entrada en el Registro.`,
    loteOmitidas: (lista: Parametro) => `Quedan pendientes: ${lista}.`,
    loteRechazadas: (n: Parametro) => `${n} rechazadas. Cada autor verá el motivo.`,
    rechazarVarias: (n: Parametro) => `Rechazar ${n} propuestas con un motivo común`,
    motivoComun: 'Motivo que verán los autores',
    phMotivo: 'Ej.: la foto es del hidrante de al lado, HID-0087',
    avisoNombres: 'No menciones a otros voluntarios: el autor lo leerá tal cual.',
    propuestoPor: (autor: Parametro, hace: Parametro, nucleo: Parametro) =>
      `Propuesto por ${autor} · ${hace} · ${nucleo}`,
    seleccionar: (nombre: Parametro) => `Seleccionar ${nombre}`,
    seleccionarTodas: 'Seleccionar todas',
    soloLectura: 'Historial: solo lectura',
    filtrar: 'Filtrar:',
    filtroOperacion: 'Filtrar por operación',
    filtroNucleo: 'Filtrar por núcleo',
    filtroEstado: 'Estado de las propuestas',
    eligeUna: 'Selecciona una propuesta de la lista.',
    historialVacio: 'Todavía no hay propuestas en este estado.',
    busquedaVacia: (texto: Parametro) => `Nada coincide con "${texto}".`,
    filtroVacio: 'No queda ninguna propuesta pendiente con ese filtro.',
    cargando: 'Cargando…',
    fotoVoluntario: 'Foto del voluntario · toca para ampliar',
    fotoSinDatos: 'Esta propuesta no trae foto nueva.',
    corrigeYAprueba:
      'Corrige lo que haga falta y aprueba en un paso. Lo cambiado queda en el registro y lo ve el autor.',
    fusionTitulo: (codigo: Parametro) => `Fusionar con ${codigo}`,
    fusionExplica: (codigo: Parametro) =>
      `${codigo} conserva su código, recibe la foto nueva y queda revisado hoy. Para cada campo que difiere, elige qué prevalece.`,
    fusionar: 'Fusionar',
    propuesta: 'Propuesta',
    existente: (codigo: Parametro, distancia: Parametro) => `${codigo} existente · a ${distancia}`,
    valorExistente: (valor: Parametro) => `${valor} (existente)`,
    valorPropuesta: (valor: Parametro) => `${valor} (propuesta)`,
    campoUbicacion: 'Ubicación',
    aprobada: (codigo: Parametro) => `Aprobada ${codigo}. Consta en el registro; el autor lo verá en su móvil.`,
    aprobadaConCorrecciones: (codigo: Parametro) => `Aprobada con correcciones ${codigo}.`,
    rechazadaAviso: 'Rechazada. El autor verá el motivo en su móvil.',
    fusionada: (codigo: Parametro) => `Fusionada con ${codigo}: no se ha creado un punto nuevo y queda revisado hoy.`,
    decididaAprobada: (quien: Parametro, cuando: Parametro) => `✓ Aprobada por ${quien} · ${cuando}`,
    decididaRechazada: (quien: Parametro, cuando: Parametro) => `✕ Rechazada por ${quien} · ${cuando}`,
    decididaRetirada: (cuando: Parametro) => `↩ Retirada por el autor · ${cuando}`,
    motivo: (texto: Parametro) => `Motivo: "${texto}"`,
    conCorrecciones: (texto: Parametro) => `Con correcciones: ${texto}`,
    fusionadaCon: (codigo: Parametro) => `Fusionada con ${codigo}. No se creó un punto nuevo.`,
    codigoAsignado: (codigo: Parametro) => `Código asignado: ${codigo}`,
    constaRegistro: 'Consta en el Registro. Solo lectura.',
    minimapa: 'Pin propuesto y puntos aprobados alrededor',
    senales: 'Señales de fiabilidad',
    senalAviso: 'con avisos',
  },

  panelInventario: {
    bocasDeRiego: 'Bocas de riego',
    filtroRevision: 'Revisión',
    todas: 'Todas',
    filtroDiametro: 'Filtrar por diámetro',
    cualquierDiametro: 'cualquier Ø',
    vista: 'Vista',
    tabla: 'Tabla',
    mapa: 'Mapa',
    colCodigo: 'Código',
    colTipo: 'Tipo',
    colDiametro: 'Diámetro',
    colEstado: 'Estado',
    colNucleo: 'Núcleo',
    colMunicipio: 'Municipio',
    colRevision: 'Última revisión',
    colAcciones: 'Acciones',
    colLat: 'Latitud',
    colLng: 'Longitud',
    albolote: 'Albolote',
    calicasas: 'Calicasas',
    ordenarPor: (columna: Parametro) => `Ordenar por ${columna}`,
    direccionDe: (codigo: Parametro) => `Dirección de ${codigo}`,
    ayudaTabla: 'pulsa una columna para ordenar · la dirección se edita en la propia celda',
    paginas: 'Páginas',
    vacio: 'No hay puntos con esos filtros.',
    guardado: (codigo: Parametro) => `Guardado ${codigo}.`,
    retirado: (codigo: Parametro) => `${codigo} retirado. Sigue en el histórico.`,
    borrado: (codigo: Parametro) => `${codigo} está en la papelera.`,
    avisoRetirar: 'El punto existió y ya no está: desaparece del mapa y se conserva en el histórico.',
    avisoBorrar: 'El registro nunca debió existir: va a la papelera y se puede restaurar mientras esté en plazo.',
    motivo: 'Motivo (obligatorio, queda en el registro)',
    sinMotivo: 'Sin motivo no se puede continuar.',
    exportado: (n: Parametro) => `Exportadas ${n} filas. La exportación consta en el Registro.`,
  },

  panelCaducadas: {
    resumen: (n: Parametro) => `${n} puntos sin revisar desde hace más de los meses configurados`,
    dePuntos: (n: Parametro) => `de ${n} puntos del núcleo`,
    verPuntos: 'Ver puntos',
    hoja: 'Hoja',
    hojaDeTodos: 'Hoja de campo de todos los núcleos',
    imprimir: 'Imprimir',
    cerrarHoja: 'Cerrar',
    tituloHoja: (nucleo: Parametro) => `Hoja de campo · ${nucleo}`,
    subtituloHoja: (n: Parametro, fecha: Parametro) => `${n} puntos por revisar · impresa el ${fecha}`,
    colSitio: 'Dirección o coordenadas',
    colUltimoEstado: 'Último estado conocido',
    colAnotar: 'Anotar revisión',
    revisado: (hace: Parametro, fecha: Parametro) => `revisado ${hace} (${fecha})`,
    ayudaHoja: 'La hoja se abre para imprimir: una página por núcleo, con una casilla en blanco para anotar.',
    vacio: 'No hay revisiones caducadas. Todo al día.',
  },

  panelRegistro: {
    filtroAccion: 'Filtrar por acción',
    todasAcciones: 'todas las acciones',
    entradas: (n: Parametro) => `${n} entradas`,
    inmutable: 'no se puede editar ni borrar',
    colMomento: 'Momento',
    colActor: 'Actor',
    colAccion: 'Acción',
    colPunto: 'Punto',
    colDetalle: 'Detalle',
    porPagina: (n: Parametro) => `${n} entradas por página`,
    vacio: 'Todavía no hay entradas con ese filtro.',
    propuestaCreada: 'Propuesta',
    propuestaRetiradaAutor: 'Propuesta retirada por su autor',
    aprobacion: 'Aprobación',
    aprobacionCorrecciones: 'Aprobación con correcciones',
    rechazo: 'Rechazo',
    fusion: 'Fusión',
    edicionAdmin: 'Edición directa',
    retirada: 'Retirada',
    borrado: 'Borrado',
    restauracion: 'Restauración',
    purgaPapelera: 'Purga de la papelera',
    codigoCambiado: 'Código de acceso cambiado',
    dispositivosRevocados: 'Dispositivos revocados',
    administradorAlta: 'Administrador añadido',
    administradorBaja: 'Administrador desactivado',
    configCambiada: 'Parámetros cambiados',
    incidenciaResuelta: 'Incidencia resuelta',
    anonimizacion: 'Anonimización',
    exportacion: 'Exportación',
    workflowLanzado: 'Mantenimiento lanzado',
  },

  panelPapelera: {
    explicacion: (dias: Parametro) => `Los borrados se conservan ${dias} días y después se purgan.`,
    purgarCaducado: 'Purgar lo caducado…',
    confirmarPurga: 'Purgar ahora',
    avisoPurga: (dias: Parametro) =>
      `Se borran definitivamente, con sus propuestas y sus fotos, los puntos que llevan más de ${dias} días en la papelera. No se puede deshacer.`,
    purgados: (n: Parametro) => `${n} puntos purgados.`,
    restaurado: (codigo: Parametro) => `${codigo} restaurado: vuelve al mapa.`,
    colBorrado: 'Borrado',
    quedan: (dias: Parametro) => `quedan ${dias} días`,
    vacia: 'La papelera está vacía.',
  },

  panelVoluntarios: {
    actividadDe: 'Actividad de los últimos',
    meses: (n: Parametro) => `${n} meses`,
    soloAqui: 'Solo visible aquí. No es un ranking público.',
    colVoluntario: 'Voluntario',
    colPropuestas: 'Propuestas',
    colAprobadas: 'Aprobadas',
    colRechazadas: 'Rechazadas',
    colTasa: 'Tasa',
    colUltima: 'Última',
    porcentaje: (n: Parametro) => `${n} %`,
    sinResolver: 'sin resolver todavía',
    convieneHablar: 'conviene explicarle mejor el formulario',
    vacio: 'Nadie ha propuesto nada en este periodo.',
    avisoAnonimizar: (autor: Parametro) =>
      `Las propuestas y el registro de ${autor} pasarán a nombre de "voluntario dado de baja". Los datos de los hidrantes se conservan. No se puede deshacer.`,
    confirmarAnonimizar: 'Anonimizar',
    anonimizado: (n: Parametro) => `Anonimizado: ${n} filas actualizadas.`,
    incidencias: 'Incidencias de la aplicación',
    deAlgoNoFunciona: 'lo que llega desde "Algo no funciona"',
    abiertas: (n: Parametro) => `${n} abiertas`,
    sinIncidencias: 'No hay incidencias. Nadie ha avisado de nada.',
    colCuando: 'Cuándo',
    colVersion: 'Versión · pantalla',
    colDescripcion: 'Descripción',
    abierta: 'abierta',
    resuelta: 'resuelta',
    resueltaPor: (quien: Parametro, cuando: Parametro) => `${quien} · ${cuando}`,
    incidenciaResuelta: 'Incidencia marcada como resuelta.',
  },

  panelAjustes: {
    codigoAcceso: 'Código de acceso',
    cambiadoPor: (fecha: Parametro, quien: Parametro, moviles: Parametro) =>
      `Cambiado por última vez el ${fecha} por ${quien}. ${moviles} móviles registrados.`,
    sinCambios: (moviles: Parametro) => `Sin cambios desde el arranque. ${moviles} móviles registrados.`,
    ver: 'ver',
    ocultar: 'ocultar',
    explicaSinRevocar:
      'Sin revocar: quien ya entró sigue trabajando y solo los móviles nuevos necesitan el código nuevo.',
    explicaRevocando: 'Revocando: todos vuelven a teclearlo. Es lo que se usa si el código se ha filtrado.',
    avisoSinRevocar: 'Se pondrá en vigor un código nuevo. Los móviles que ya tienen acceso siguen funcionando.',
    avisoRevocando: (moviles: Parametro) =>
      `Se pondrá en vigor un código nuevo y ${moviles} móviles tendrán que volver a escribirlo al abrir la aplicación. Sus nombres se conservan.`,
    confirmarCodigo: 'Generar y poner en vigor',
    codigoCambiado: (codigo: Parametro) => `Código nuevo en vigor: ${codigo}. Comunícalo al grupo.`,
    administradores: 'Acceso de administradores',
    ayudaAdministradores: 'Lista propia de hidrantes, independiente de la app de uniformidad.',
    anadidoEl: (fecha: Parametro, quien: Parametro) => `añadido el ${fecha} por ${quien}`,
    accesoDe: (correo: Parametro) => `Acceso de ${correo}`,
    activo: 'activo',
    sinAcceso: 'sin acceso',
    correoNuevo: 'correo@albolote-pc.es',
    sugerencias: 'Sugerencias de la app de uniformidad:',
    administradorAnadido: (correo: Parametro) => `${correo} ya puede entrar en el panel.`,
    administradorQuitado: (correo: Parametro) => `${correo} se queda sin acceso al panel.`,
    parametros: 'Parámetros',
    ayudaParametros: 'Los móviles los aplican en su próxima sincronización.',
    mesesRevision: 'Meses entre revisiones',
    radioDuplicado: 'Radio de duplicado (m)',
    diasPapelera: 'Días de papelera',
    bufferZona: 'Margen de la zona (m)',
    subidasDia: 'Fotos por móvil y día',
    metrosTramo: 'Tramo de manguera (m)',
    radiosMarcador: 'Radios de marcador (px)',
    fueraDeRango: (campo: Parametro) => `"${campo}" está fuera de rango.`,
    parametrosGuardados: 'Parámetros guardados.',
    nucleos: 'Núcleos',
    ayudaNucleos: 'Deducidos de OpenStreetMap. Se puede renombrar uno o añadir el que falte.',
    nPuntos: (n: Parametro) => `${n} puntos`,
    anadidoAMano: 'añadido a mano',
    renombrar: 'Renombrar',
    nombreDe: (nucleo: Parametro) => `Nombre de ${nucleo}`,
    anadirNucleo: 'Añadir un núcleo',
    nombreNucleo: 'Nombre del núcleo',
    tocaDondeEsta:
      'Toca el mapa en el centro del núcleo: de ahí sale el municipio y a qué núcleo pertenece cada punto.',
    pinNucleo: 'Centro del núcleo',
    faltaNombre: 'Escribe el nombre del núcleo',
    faltaPosicion: 'Toca el mapa para situarlo',
    nucleoAnadido: (nombre: Parametro) => `Núcleo "${nombre}" añadido.`,
    nucleoRenombrado: (antes: Parametro, ahora: Parametro) => `"${antes}" ahora se llama "${ahora}".`,
    pendientes14: 'Propuestas pendientes de más de 14 días',
    incidenciasAbiertas: 'Incidencias abiertas',
    errores7: 'Errores de la aplicación (7 días)',
    sinDireccion: 'Puntos sin dirección deducida',
    ultimoRespaldo: 'Último respaldo',
    ultimaVigilancia: 'Última vigilancia',
    vigilanciaBien: 'todo respondía',
    vigilanciaMal: 'con avisos: mira las issues',
    almacenamiento: 'Almacenamiento usado',
    almacenamientoLleno: (porcentaje: Parametro) =>
      `Las fotos ocupan el ${porcentaje} % del gigabyte gratuito. Purga la papelera y las fotos huérfanas antes de que se llene: mientras esté lleno, la aplicación no admite fotos nuevas.`,
    zonaYMapa: 'Zona de cobertura · mapa base',
    callejero: 'Callejero sin conexión',
    dispositivosActivos: 'Móviles con acceso',
    intentosFallidos24h: 'Códigos de acceso fallidos (24 h)',
    baseDeDatos: 'Base de datos',
    baseDeDatosDetalle: (mb: Parametro, total: Parametro) => `${mb} MB de ${total} MB`,
    tareasProgramadas: 'Tareas programadas',
    tareaBien: (hace: Parametro) => `${hace} · bien`,
    tareaMal: (hace: Parametro) => `${hace} · falló o va con retraso`,
    tareaSinEjecutar: 'todavía sin ejecutar',
    tareaFalta: 'no está programada',
    topesAlcanzados24h: 'Entradas bloqueadas por demasiados intentos (24 h)',
    topesDetalle: (n: Parametro, grupo: Parametro) => `${n} · de todo el grupo: ${grupo}`,
    nunca: 'todavía ninguno',
    // En staging no se hacen respaldos: solo de producción (docs/20 RV-78).
    respaldoNoAplica: 'no se respalda: entorno de pruebas',
    sinDato: 'sin dato',
    inventarioDescargado: (n: Parametro) => `Inventario descargado: ${n} puntos.`,
    mantenimiento: 'Mantenimiento',
    ayudaMantenimiento:
      'Se ejecutan fuera de la aplicación y tardan unos minutos. El resultado aparece en Salud del sistema y en el Registro.',
    trabajoLanzado: (nombre: Parametro) => `"${nombre}" lanzado. Tarda unos minutos.`,
    avisosJefatura: 'Avisos para jefatura',
    ayudaAvisos: 'Notificaciones en este navegador. Opcionales y apagadas por defecto.',
    nuevasPropuestas: 'Nuevas propuestas pendientes',
    agrupadas: 'agrupadas: como mucho una por hora',
    resumenSemanal: 'Resumen semanal',
    losLunes: 'los lunes: revisiones caducadas y pendientes antiguas',
    avisosDenegados: 'Este navegador tiene los avisos bloqueados. Actívalos en la configuración del sitio.',
    avisosInstalar: 'En iPhone hay que instalar la aplicación en la pantalla de inicio para recibir avisos.',
    avisosNoDisponibles: 'Este navegador no admite avisos.',
    avisosNoActivados: 'No se han podido activar los avisos.',
    codigoQr: 'Código QR del enlace',
    ayudaQr: 'Para la sede y las reuniones: quien lo escanea abre la aplicación.',
    imprimirA4: 'Imprimir A4',
    escaneaParaInstalar: 'Escanea para instalar',
    pieCartel: 'Mapa de hidrantes y bocas de riego. Entra con el código de acceso que te haya dado jefatura.',
    novedades: 'Novedades',
    ayudaNovedades: 'Lo que cambió en las últimas versiones.',
    sinNovedades: 'Todavía no hay novedades publicadas.',
  },

  panelErrores: {
    yaResuelta: 'Esta propuesta ya no está pendiente: otra persona la ha resuelto. La lista se ha actualizado.',
    puntoNoActivo: 'El punto ya no está activo.',
    desactualizada: 'El punto cambió mientras revisabas: vuelve a mirar el detalle y confirma.',
    motivo: 'Sin motivo no se puede continuar.',
    tipoDistinto: 'Solo se fusionan puntos del mismo tipo.',
    soloAltas: 'Solo se puede fusionar un alta.',
    datos: 'El resultado no cumple las reglas del punto: revisa los valores.',
    fueraDePlazo: 'Ha pasado el plazo de la papelera: ya no se puede restaurar.',
    codigoFormato: 'El código son 6 cifras.',
    config: 'Algún valor está fuera de rango: revisa los parámetros.',
    noAutorizado: 'Tu cuenta ya no tiene acceso de administrador.',
    noConfigurado: 'Esta acción aún no está configurada en el servidor.',
    sinServidor: 'Sin conexión con el servidor. Inténtalo de nuevo en un momento.',
    puntoOcupado: 'Otra persona está cambiando este punto; inténtalo en unos segundos.',
    tipoNoModificable: 'El tipo de un punto no se cambia: retíralo y da de alta el correcto.',
    generico: 'No se ha podido completar. Inténtalo de nuevo.',
  },

  panel: {
    titulo: 'Hidrantes Albolote · Panel de jefatura',
    atribucion: 'Direcciones deducidas con Nominatim · © OpenStreetMap contributors',
    salir: 'Cerrar sesión',
    sinServidor: 'Sin conexión con el servidor',
    datosDe: (hace: Parametro) => `datos de ${hace}`,
    editar: 'Editar',
    retirar: 'Retirar',
    borrar: 'Borrar',
    historial: 'Historial',
    restaurar: 'Restaurar',
    borrarDefinitivamente: 'Borrar definitivamente…',
    vaciarPapelera: 'Vaciar la papelera…',
    marcarResuelta: 'Marcar resuelta',
    anonimizar: 'Anonimizar…',
    hojaDeCampo: 'Hoja de campo por núcleo',
    exportar: 'Exportar',
    excel: 'Excel',
    csv: 'CSV',
    geojson: 'GeoJSON',
    descargarInventario: 'Descargar inventario (JSON)',
    purgarFotos: 'Purgar fotos huérfanas',
    generarNuevo: 'Generar uno nuevo',
    revocarTodos: 'Revocar todos los dispositivos',
    guardarCambios: 'Guardar cambios',
    anadir: 'Añadir',
    regenerarZona: 'Regenerar zona de cobertura',
    regenerarMapaBase: 'Regenerar mapa base',
    respaldoAhora: 'Respaldo ahora',
    saludSistema: 'Salud del sistema',
    mostrando: (n: Parametro, total: Parametro) => `Mostrando ${n} de ${total} puntos`,
    ultimoAdministrador: 'No se puede desactivar al último administrador activo.',
    pendienteEscribe: '— pendiente, escribe aquí',
  },
} as const;
