// Todos los textos de interfaz (UI-20, TR-111). Literales del Apéndice A de docs/06 (UI-21).
// Una cadena nueva se añade aquí Y al Apéndice A en el mismo PR: textos.test.ts lo comprueba.
// Lo que va entre corchetes en el apéndice es un parámetro de la función correspondiente.

type Parametro = string | number;

export const T = {
  app: {
    nombre: 'Protección Civil Albolote',
    nombreCorto: 'Hidrantes',
    entornoPruebas: 'ENTORNO DE PRUEBAS',
  },

  navegacion: {
    mapa: 'Mapa',
    lista: 'Lista',
    ajustes: 'Ajustes',
    puntosDeAgua: 'Puntos de agua',
    misPropuestas: 'Mis propuestas',
    nuevoPunto: 'Nuevo punto',
    jefatura: 'Jefatura',
  },

  entrada: {
    codigo: 'Código de acceso del grupo',
    nombre: 'Nombre',
    apellido: 'Apellido',
    entrar: 'Entrar',
    soloUnaVez: 'Solo se pide una vez: este móvil recordará tu acceso y tu nombre.',
    jefaturaGoogle: '¿Eres de jefatura? Entrar con Google',
    avisoLegal: 'Aviso legal y privacidad',
    codigoIncorrecto: 'Código incorrecto',
    demasiadosIntentos: 'Demasiados intentos. Espera una hora antes de volver a intentarlo.',
    noAutorizado: 'No autorizado',
    noAutorizadoDetalle:
      'Tu cuenta de Google no está en la lista de administradores de hidrantes. Pide a jefatura que la añada desde Ajustes del panel.',
  },

  mapa: {
    buscar: 'Buscar código, calle o descripción…',
    capas: 'Capas',
    mapaBasePropio: 'Mapa base propio',
    calleOsm: 'Calle (OSM)',
    satelitePnoa: 'Satélite (PNOA)',
    catastro: 'Catastro',
    necesitaCobertura: 'necesita cobertura',
    miPosicion: 'Mi posición',
    sincronizado: (hace: Parametro) => `Sincronizado ${hace}`,
    sinCobertura: (hace: Parametro) => `Sin cobertura · datos de ${hace}`,
    sinServidor: 'Sin conexión con el servidor',
    sinEnviar: (n: Parametro) => `${n} sin enviar`,
    todos: 'Todos',
    hidrantes: 'Hidrantes',
    bocas: 'Bocas',
    noFunciona: 'No funciona',
    sinRevisar: 'Sin revisar',
    leyendaTamano: 'Más grande = más agua aprovechable',
    desdeTi: 'desde ti',
    filtroVacio: 'Nada coincide con ese filtro.',
  },

  ficha: {
    direccion: 'Dirección',
    ultimaRevision: 'Última revisión',
    aTi: 'A ti',
    sinDireccion: 'sin dirección',
    caducada: 'caducada',
    proponerCambio: 'Proponer un cambio',
    comoLlegar: 'Cómo llegar',
    datosDe: (hace: Parametro) => `Datos de ${hace} · sin cobertura`,
    ampliar: 'ampliar',
  },

  operaciones: {
    queHaCambiado: (codigo: Parametro) => `¿Qué ha cambiado en ${codigo}?`,
    sigueIgual: 'Sigue igual',
    sigueIgualDetalle: 'Solo actualiza la fecha de revisión. Foto y listo.',
    actualizarEstado: 'Actualizar estado',
    actualizarEstadoDetalle: 'El caudal ha cambiado o ya no funciona',
    corregirDatos: 'Corregir datos',
    corregirDatosDetalle: 'Tipo, diámetro o racor mal anotados',
    corregirUbicacion: 'Corregir ubicación',
    corregirUbicacionDetalle: 'El pin está desplazado',
    proponerRetirada: 'Proponer retirada',
    proponerRetiradaDetalle: 'Ya no existe. Pide un motivo breve',
  },

  formulario: {
    tipoElemento: 'Tipo de elemento',
    hidrante: 'Hidrante',
    bocaRiego: 'Boca de riego',
    diametro: 'Diámetro de la salida mayor',
    d70: '70 mm',
    d100: '100 mm',
    otraMedida: 'Otra medida',
    diametroAyuda: 'La salida, no la tubería. Si hay varias, marca la mayor',
    diametroBoca: '45 mm · fijo en bocas de riego',
    racor: 'Racor · compara con lo que ves',
    granada: 'Granada',
    barcelona: 'Barcelona',
    otro: 'Otro',
    caudal: 'Caudal / estado',
    bueno: 'Bueno',
    regular: 'Regular',
    malo: 'Malo',
    noFunciona: 'No funciona',
    caudalAyuda: 'Malo = probado y sale débil. No funciona = no se pudo probar (tapa, válvula, arqueta).',
    descripcionFallo: 'Descripción del fallo · obligatoria',
    foto: 'Foto',
    fotoDeHoy: 'Foto de hoy',
    fotoDelSitio: 'Foto del sitio',
    hacerFoto: 'Hacer foto · obligatoria',
    fotoAnadida: (kb: Parametro) => `Foto añadida · ${kb} kB`,
    repetir: 'repetir',
    descripcionOpcional: 'Descripción (opcional)',
    descripcionAyuda: 'Referencia de calle, acceso…',
    notaOpcional: 'Nota (opcional)',
    desplazamiento: 'Desplazamiento',
    tuGps: 'Tu GPS',
    porQueRetirada: '¿Por qué ya no existe?',
    obras: 'Obras',
    asfaltado: 'Asfaltado',
    sustituido: 'Sustituido',
    motivoRetirada: 'Cuéntalo brevemente · obligatorio',
  },

  avisosFormulario: {
    faltaFoto: 'Falta la foto para poder enviar',
    eligeEstado: 'Elige el estado',
    describeFallo: 'Describe el fallo',
    eligeTipo: 'Elige el tipo',
    eligeDiametro: 'Elige el diámetro',
    indicaMedida: 'Indica la medida',
    eligeRacor: 'Elige el racor',
    muevePin: 'Mueve el pin al sitio correcto',
    sinCambios: 'No has cambiado nada',
    fueraDeZona: '⚠ Esto queda fuera de la zona habitual. Puedes continuar; jefatura lo verá señalado.',
    ajustaPin: (metros: Parametro) => `Toca el mapa para ajustar el pin · el círculo azul es tu GPS (±${metros} m)`,
  },

  envio: {
    enviarRevision: 'Enviar para revisión',
    enviarRetirada: 'Enviar propuesta de retirada',
    aplicarAhora: 'Aplicar ahora',
    guardarSinCobertura: 'Guardar · se enviará con cobertura',
    guardarSinServidor: 'Guardar · se enviará al volver el servidor',
    enviado: 'Enviado para revisión',
    guardadoEnMovil: 'Guardado en el móvil',
    aplicado: 'Aplicado',
    volverAlMapa: 'Volver al mapa',
    verMisPropuestas: 'Ver mis propuestas',
    jefaturaRevisara: 'Jefatura lo revisará. Te avisaremos del resultado al abrir la aplicación.',
    avisoSinCobertura: 'Sin cobertura · lo que envíes se guardará en el móvil y saldrá al recuperar señal',
    avisoSinServidor:
      'Sin conexión con el servidor · seguimos con los datos guardados; lo que envíes esperará y se reintentará solo',
  },

  misPropuestas: {
    pendiente: 'Pendiente',
    aprobada: 'Aprobada',
    rechazada: 'Rechazada',
    retiradaPorTi: 'Retirada por ti',
    sinEnviar: 'Sin enviar',
    retirar: 'Retirar',
    motivo: (texto: Parametro) => `Motivo: ${texto}`,
    conCorrecciones: (texto: Parametro) => `con correcciones: ${texto}`,
    esperando24h: '⚠ Lleva más de 24 h esperando cobertura. Se enviará sola al tener señal.',
    vacio: 'Todavía no has propuesto nada. Desde la ficha de un punto o con el botón + del mapa.',
  },

  ajustes: {
    firma: 'Firma de tus propuestas',
    cambiar: 'Cambiar',
    mapaSinCobertura: 'Mapa sin cobertura',
    descargado: (mb: Parametro, fecha: Parametro) => `Descargado · ${mb} MB · ${fecha}`,
    noDescargado: 'No descargado',
    descargar: 'Descargar',
    actualizar: 'Actualizar',
    puntosGuardados: 'Puntos guardados',
    sincronizar: 'Sincronizar',
    capaPorDefecto: 'Capa por defecto',
    modoOscuro: 'Modo oscuro',
    segunMovil: 'Según el móvil',
    avisarResolucion: 'Avisarme cuando jefatura resuelva mis propuestas',
    algoNoFunciona: 'Algo no funciona en la aplicación',
    avisarJefatura: 'Avisar a jefatura',
    comoSeUsa: 'Cómo se usa (3 pantallas)',
    cerrarSesion: 'Cerrar sesión en este móvil',
    cerrarSesionDetalle: 'Se borran tu acceso, tu nombre y los puntos guardados.',
    versionNueva: 'hay una versión nueva, recargar',
    novedades: 'novedades',
  },

  panelCola: {
    colaRevision: 'Cola de revisión',
    inventario: 'Inventario',
    revisionesCaducadas: 'Revisiones caducadas',
    registro: 'Registro',
    papelera: 'Papelera',
    voluntarios: 'Voluntarios',
    ajustes: 'Ajustes',
    buscar: 'Buscar código, calle o voluntario…',
    pendientes: 'Pendientes',
    aprobadas: 'Aprobadas',
    rechazadas: 'Rechazadas',
    retiradasPorAutor: 'Retiradas por el autor',
    ningunaSeleccionada: 'Ninguna seleccionada',
    seleccionadas: (n: Parametro) => `${n} seleccionadas`,
    aprobarSeleccionadas: 'Aprobar seleccionadas',
    rechazarSeleccionadas: 'Rechazar seleccionadas…',
    todasOperaciones: 'todas las operaciones',
    todosNucleos: 'todos los núcleos',
    aprobar: 'Aprobar',
    aprobarConCorrecciones: 'Aprobar con correcciones',
    guardarYAprobar: 'Guardar y aprobar',
    rechazar: 'Rechazar…',
    confirmarRechazo: 'Confirmar rechazo',
    fusionarCon: (codigo: Parametro) => `Fusionar con ${codigo}`,
    confirmarYAprobar: 'Confirmar y aprobar',
    cancelar: 'Cancelar',
    motivoRechazo: 'Motivo del rechazo (obligatorio, lo verá quien lo propuso)',
    sinMotivo: 'Sin motivo no se puede rechazar.',
    desactualizada: (cuando: Parametro) =>
      `El diff está calculado sobre un estado que ya no existe: el punto cambió ${cuando}. Se pide confirmación expresa en lugar del botón normal.`,
    posibleDuplicado: 'Posible duplicado: compara antes de decidir. En ámbar, lo que difiere.',
    colaVacia: 'No queda ninguna propuesta pendiente. Buen trabajo.',
    deducidaEditable: 'deducida · editable',
    delPunto: 'del punto',
  },

  panel: {
    editar: 'Editar',
    retirar: 'Retirar',
    borrar: 'Borrar',
    historial: 'Historial',
    restaurar: 'Restaurar',
    borrarDefinitivamente: 'Borrar definitivamente…',
    vaciarPapelera: 'Vaciar la papelera…',
    marcarResuelta: 'Marcar resuelta',
    anonimizar: 'Anonimizar…',
    hojaDeCampo: 'Hoja de campo por núcleo',
    exportar: 'Exportar',
    excel: 'Excel',
    csv: 'CSV',
    geojson: 'GeoJSON',
    descargarInventario: 'Descargar inventario (JSON)',
    purgarFotos: 'Purgar fotos huérfanas',
    generarNuevo: 'Generar uno nuevo',
    revocarTodos: 'Revocar todos los dispositivos',
    guardarCambios: 'Guardar cambios',
    anadir: 'Añadir',
    regenerarZona: 'Regenerar zona de cobertura',
    regenerarMapaBase: 'Regenerar mapa base',
    respaldoAhora: 'Respaldo ahora',
    saludSistema: 'Salud del sistema',
    mostrando: (n: Parametro, total: Parametro) => `Mostrando ${n} de ${total} puntos`,
    ultimoAdministrador: 'No se puede desactivar al último administrador activo.',
    pendienteEscribe: '— pendiente, escribe aquí',
  },
} as const;
